# Generated by Django 4.0.4 on 2022-05-05 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submited_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
